# Generated by Django 3.2.4 on 2021-08-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='picture',
            field=models.ImageField(default='profile/default_user.png', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
