# Generated by Django 3.2.4 on 2021-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='picture',
            field=models.ImageField(default='sfdsf', upload_to='profile'),
            preserve_default=False,
        ),
    ]
