# Generated by Django 3.2.4 on 2021-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210813_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_info',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
